### ISSUE TITLE
로그인 여부에 따른 리다이렉트 처리

### ISSUE THREAD

**Issue by rlawogns123** [Wanted-Pre-Onboarding-FE-Team-12/week1-1-best-practice#10]
## 🔨 설명
토큰 검사할 때 페이지가 /auth 페이지로 하셨는데 과제 안내에는 / 페이지로 되어 있습니다!
## 📑 완료 조건

1.

**Comment by CH4MD0M** [comment]
제가 마음대로 작성해버린 코드네요ㅠ 재훈님 말씀대로 요구사항에 맞춰 작성하는게 좋을것 같습니다👍
