### ISSUE TITLE
env 환경변수 설정

### ISSUE THREAD

**Issue by jiye-7** [Wanted-Pre-Onboarding-FE-Team-12/week1-1-best-practice#6]
## 🔨 설명
.env 를 이용한 환경변수 설정

## 📑 완료 조건
1. REACT_APP_API_URL=https://n38lcff1wk.execute-api.ap-northeast-2.amazonaws.com/

**Comment by jinux127** [comment]
오..좋아요..사실 env는 gitignore에 추가해서 안보이게 하는게 국룰이지만 이미 노출된 url이기도하고 저희는 실제 서비스가 아니니 좋은것 같습니다~!
